; This file was auto-generated by drush make
core = 7.15
api = 2

; Modules
projects[views_bulk_operations][version] = "3.0-rc1"
projects[views_bulk_operations][subdir] = contrib

projects[addressfield][version] = "1.0-beta3"
projects[addressfield][subdir] = contrib

projects[admin][version] = "2.0-beta3"
projects[admin][subdir] = contrib

projects[admin_menu][version] = "3.0-rc3"
projects[admin_menu][subdir] = contrib

projects[advanced_help][version] = "1.0"
projects[advanced_help][subdir] = contrib

projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][subdir] = contrib

projects[ctools][version] = "1.1"
projects[ctools][subdir] = contrib

projects[commerce][version] = "1.3"
projects[commerce][subdir] = contrib

projects[commerce_stock][version] = "1.1"
projects[commerce_stock][subdir] = contrib

projects[content_access][version] = "1.2-beta1"
projects[content_access][subdir] = contrib

projects[context][version] = "3.0-beta4"
projects[context][subdir] = contrib

projects[date][version] = "2.6"
projects[date][subdir] = contrib

projects[devel][version] = "1.3"
projects[devel][subdir] = contrib

projects[diff][version] = "2.0"
projects[diff][subdir] = contrib

projects[entity][version] = "1.0-rc3"
projects[entity][subdir] = contrib

projects[entityreference][version] = "1.0-rc3"
projects[entityreference][subdir] = contrib

projects[entityreference_prepopulate][version] = "1.0"
projects[entityreference_prepopulate][subdir] = contrib

projects[features][version] = "1.0"
projects[features][subdir] = contrib

projects[field_group][version] = "1.1"
projects[field_group][subdir] = contrib

projects[field_permissions][version] = "1.0-beta2"
projects[field_permissions][subdir] = contrib

projects[flag][version] = "2.0-beta8"
projects[flag][subdir] = contrib

projects[link][version] = "1.0"
projects[link][subdir] = contrib

projects[panels][version] = "3.2"
projects[panels][subdir] = contrib

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = contrib

projects[quicktabs][version] = "3.4"
projects[quicktabs][subdir] = contrib

projects[rules][version] = "2.2"
projects[rules][subdir] = contrib

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = contrib

projects[token][version] = "1.2"
projects[token][subdir] = contrib

projects[views][version] = "3.3"
projects[views][subdir] = contrib

projects[views_send][version] = "1.0-alpha1"
projects[views_send][subdir] = contrib

projects[views_data_export][version] = "3.0-beta6"
projects[views_data_export][subdir] = contrib

projects[webform][version] = "3.18"
projects[webform][subdir] = contrib

; Themes
projects[adaptivetheme][version] = "2.2"

; Git sourced Modules
projects[cod_support][type] = "module"
projects[cod_support][subdir] = contrib
projects[cod_support][download][type] = "git"
projects[cod_support][download][url] = "http://git.drupal.org/project/cod_support.git"
projects[cod_support][download][branch] = "7.x-1.x"

projects[registration][type] = "module"
projects[registration][subdir] = contrib
projects[registration][download][type] = "git"
projects[registration][download][url] = "http://git.drupal.org/project/registration.git"
projects[registration][download][branch] = "7.x-1.x"

projects[uuid][type] = "module"
projects[uuid][subdir] = contrib
projects[uuid][download][type] = "git"
projects[uuid][download][url] = "http://git.drupal.org/project/uuid.git"
projects[uuid][download][branch] = "7.x-1.x"

projects[uuid_features][type] = "module"
projects[uuid_features][subdir] = contrib
projects[uuid_features][download][type] = "git"
projects[uuid_features][download][url] = "http://git.drupal.org/project/uuid_features.git"
projects[uuid_features][download][branch] = "7.x-1.x"