<?php

/**
* Implements hook_block_info().
*/
function njblocks_block_info() {

  $blocks = array(
    'footer_contact_info' => array(
      'info' => t('Contact Information for Footer'),
    ),
    'tickets_registration' => array(
      'info' => t('Saturday Camp ticket information'),
    ),
    'training_tickets' => array(
      'info' => t('Friday Training ticket information'),
    ),
     'camp_highlights' => array(
      'info' => t('Large Information about the Camp'),
    ),
    'twitter_timeline' => array(
      'info' => t('Twitter Timeline Widget'),
    ),
    'code_of_conduct' => array(
      'info' => t('Code of Conduct'),
    ),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function njblocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'footer_contact_info':
      $block['subject'] = t('Contact the Organizers') . '!';
      $block['content'] = theme('footer_contact_info');
      break;
    case 'tickets_registration':
      $block['subject'] = t('Saturday Camp Tickets');
      $block['content'] = theme('tickets_registration');
      break;
    case 'training_tickets':
      $block['subject'] = t('Friday Training Tickets');
      $block['content'] = theme('training_tickets');
      break;
    case 'camp_highlights':
      $block['subject'] = "5<sup>th</sup>".t('Annual') . "<br />" .t('DrupalCamp NJ');
      $block['content'] = theme('camp_highlights');
      break;
    case 'twitter_timeline':
      $block['content'] = theme('twitter_timeline');
      break;
    case 'code_of_conduct':
      $block['subject'] = t('Code of Conduct');
      $block['content'] = theme('code_of_conduct');
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function njblocks_theme() {
  return array(
    'footer_contact_info' => array(
      'template' => 'templates/footer_contact_info',
      'arguments' => array(),
    ),
    'tickets_registration' => array(
      'template' => 'templates/tickets_registration',
      'arguments' => array(),
    ),
    'training_tickets' => array(
      'template' => 'templates/training_tickets',
      'arguments' => array(),
    ),
    'camp_highlights' => array(
      'template' => 'templates/camp_highlights',
      'arguments' => array(),
    ),
    'twitter_timeline' => array(
      'template' => 'templates/twitter_timeline',
      'arguments' => array(),
    ),
    'code_of_conduct' => array(
      'template' => 'templates/code_of_conduct',
      'arguments' => array(),
    ),
  );
}
